rows = [l.rstrip('\n').split('|', 2) for l in open('/tmp/wc/ewkt.txt') if l.strip()]
assert len(rows) == 23
SOURCE = "CivicBrain analytical GIS units, topology-cleaned v2 (from tdmc_wards_verified.geojson; disputed areas split to nearest undisputed core)"
values = ",\n".join("      (%s, ST_GeomFromEWKT('%s'))" % (wn, ewkt) for wn, _, ewkt in rows)

sql = r"""-- =============================================================================
-- CivicBrain  |  V3__wards_topology_clean.sql
-- Ward topology clean-up: replace the 23 ANALYTICAL_GIS_23 ward polygons with a clean
-- tiling of the Talegaon Dabhade municipal boundary (geometry version 'v2').
--
-- Target  : PostgreSQL 16-18 + PostGIS 3.4+
-- Order   : run AFTER V2__civicbrain_app_layer.sql. Also works when V2 was never applied:
--           it only uses V1 columns (wards.ward_id/ward_number/source/geometry,
--           complaints.location/ward_id, pois.geometry/ward_id, roads.geometry/ward_id).
-- Run as  : the database owner, e.g.  psql -v ON_ERROR_STOP=1 -d civicbrain -f V3__wards_topology_clean.sql
--           (or place it next to V2 in src/main/resources/db/migration and let Flyway run it)
--
-- PURPOSE
--   The 23 verified ward polygons do not tile the TDMC boundary (25.26 km2):
--     * 39 ward pairs overlap (>= 1 m2; plus one 0.6 m2 touch) - 929,937 m2 in total; a point in an
--       overlap belongs to two wards, and the ward it gets depends on the query;
--     * 28 gaps inside the boundary (574,800 m2) - a point there belongs to no ward;
--     * 146,802 m2 of ward area lies outside the municipal boundary.
--   This migration stores a clean tiling (no overlaps, no gaps, nothing outside the boundary)
--   and re-derives complaints/pois/roads.ward_id from it.
--
-- METHOD (deterministic; computed offline in PostGIS 3.4 / GEOS 3.12, result embedded below)
--   1. All geometry work in EPSG:32643 (UTM 43N); inputs first densified to <= 0.0001 deg in
--      EPSG:4326 so straight lon/lat edges survive the projection round trip.
--   2. Each ward clipped to the municipal boundary.
--   3. Disputed area D = union of all pairwise ward overlaps  UNION  (boundary - union of clipped wards).
--      Core_i = clipped ward_i - D  (core parts < 1 m2 dropped and added to D).
--   4. D split by NEAREST CORE: the core edges facing D were sampled every 1 m, a Voronoi diagram
--      of the labelled samples was built and dissolved per ward, and intersected with D.
--      The Voronoi zig-zag inside D was then smoothed with a coverage-safe simplification
--      (ST_CoverageSimplify, tolerance 1 m, outline of D fixed; max shift 0.46 m).
--   5. Ward_i = core_i + its share of D, assembled as ONE snap-rounded (1 micrometre) noded coverage
--      (so neighbouring wards share identical edges), clipped to the boundary, holes < 1 m2 removed,
--      transformed back to EPSG:4326 (collinear densification vertices stripped).
--   6. Checks in EPSG:4326 (geography areas): 23 valid MultiPolygons; pairwise overlap 0 m2;
--      boundary - union 0.005 m2; union - boundary 0.004 m2; ST_CoverageInvalidEdges = 0.
--      Ward 18 keeps a detached 210.6 m2 part (>= 50 m2, so it was not merged).
--   Rule for points: a complaint / POI goes to the ward whose geometry ST_Covers it (ties on a shared
--   edge: smallest ward, then lowest ward_number - same order as fn_locate_point in V2); if no ward
--   covers it, the nearest ward (geography distance). A road goes to the ward holding the largest
--   share of its length (ties: lowest ward_number); a road touching no ward goes to the nearest ward.
--
-- NEEDS HUMAN CONFIRMATION (in QGIS, against the reference map)
--   The 4 large overlaps are not digitising slivers (average width 99-217 m); they are real
--   uncertainty about which ward the land belongs to. The nearest-core rule split them as follows:
--     13/16  311,060 m2  ->  W16 175,977 m2 (57%)  / W13 135,083 m2 (43%)
--     19/20  146,337 m2  ->  W19  81,131 m2 (55%)  / W20  65,165 m2 (45%)  (+41 m2 to W23)
--     18/19  127,993 m2  ->  W19  68,432 m2 (53%)  / W18  59,561 m2 (47%)
--     17/18   89,693 m2  ->  W18  50,209 m2 (56%)  / W17  39,484 m2 (44%)
--   Load gis/tdmc_wards_clean_v2.geojson over tdmc_boundary_georeferenced.tif and confirm each split
--   (and the 4 gaps > 50,000 m2 listed in gis/WARD_QA_REPORT.md). If the reference map disagrees, fix
--   the geometry in a later migration (V4) - do not edit this file after it has been applied.
--
-- WHAT IT CHANGES
--   * creates public.ward_geometry_history and archives the current wards.geometry (version 'v2')
--   * updates wards.geometry and wards.source, matched by ward_number (ward_id values do NOT change,
--     so every foreign key - complaints, pois, roads, officer_scopes - stays valid)
--   * creates public.ward_reassignment_log and logs every complaint / poi / road whose ward_id changes,
--     BEFORE updating it. Triggers stay enabled: trg_complaints_updated_at sets updated_at on the
--     re-assigned complaints (status is not touched, so the status guard / status log do not fire).
--   * NOTE pois.ward_id: in the current data it holds ward NUMBERS (e.g. 14) instead of wards.ward_id
--     (ward 14 has ward_id 3). The recompute corrects this; those rows appear in the log.
--   Expected on the current data: 13 complaints, 22 pois (id correction only), 65 roads re-assigned.
--
-- IDEMPOTENT: if ward_geometry_history already has rows with version = 'v2' the DO block does nothing.
-- ROLLBACK (manual, if ever needed):
--   UPDATE wards w SET geometry = h.geometry_before FROM ward_geometry_history h
--    WHERE h.version = 'v2' AND h.ward_number = w.ward_number;
--   UPDATE complaints c SET ward_id = l.old_ward_id FROM ward_reassignment_log l
--    WHERE l.entity = 'complaint' AND l.entity_id = c.complaint_id;      -- same for 'poi' / 'road'
-- =============================================================================

BEGIN;

SET LOCAL search_path = public;

CREATE TABLE IF NOT EXISTS public.ward_geometry_history (
    ward_id          bigint,
    ward_number      int,
    geometry_before  geometry(Geometry,4326),
    archived_at      timestamptz DEFAULT now(),
    version          text
);
COMMENT ON TABLE public.ward_geometry_history IS
  'Ward geometries archived before a geometry change. version = the geometry version that replaced them (v2 = topology-cleaned, V3 migration).';
CREATE INDEX IF NOT EXISTS idx_ward_geometry_history_version ON public.ward_geometry_history (version, ward_number);

CREATE TABLE IF NOT EXISTS public.ward_reassignment_log (
    entity       text,
    entity_id    bigint,
    old_ward_id  bigint,
    new_ward_id  bigint,
    logged_at    timestamptz DEFAULT now()
);
COMMENT ON TABLE public.ward_reassignment_log IS
  'One row per complaint / poi / road whose ward_id was changed by a ward geometry migration (logged before the update).';
CREATE INDEX IF NOT EXISTS idx_ward_reassignment_log_entity ON public.ward_reassignment_log (entity, entity_id);

DO $v3$
DECLARE
    v_n         bigint;
    v_total     bigint;
    v_overlap   double precision;
    v_complaint bigint;
    v_poi       bigint;
    v_road      bigint;
BEGIN
    -- ---------------------------------------------------------------- idempotency guard
    IF EXISTS (SELECT 1 FROM public.ward_geometry_history WHERE version = 'v2') THEN
        RAISE NOTICE 'V3: ward geometry version v2 is already applied (ward_geometry_history has v2 rows) - nothing to do';
        RETURN;
    END IF;

    -- ---------------------------------------------------------------- preconditions
    SELECT count(*) FILTER (WHERE ward_number BETWEEN 1 AND 23), count(*)
      INTO v_n, v_total FROM public.wards;
    IF v_n <> 23 OR v_total <> 23 THEN
        RAISE EXCEPTION 'V3: expected exactly 23 wards numbered 1..23, found % of % rows', v_n, v_total;
    END IF;

    -- ---------------------------------------------------------------- cleaned geometries (EPSG:4326)
    CREATE TEMP TABLE v3_ward_geom (
        ward_number int PRIMARY KEY,
        geom        geometry(MultiPolygon,4326) NOT NULL
    ) ON COMMIT DROP;

    INSERT INTO v3_ward_geom (ward_number, geom) VALUES
""" + values + r""";

    IF (SELECT count(*) FROM v3_ward_geom WHERE ST_IsValid(geom) AND NOT ST_IsEmpty(geom)) <> 23 THEN
        RAISE EXCEPTION 'V3: embedded ward geometries are not 23 valid, non-empty MultiPolygons';
    END IF;

    -- ---------------------------------------------------------------- 1. archive current geometries
    INSERT INTO public.ward_geometry_history (ward_id, ward_number, geometry_before, version)
    SELECT ward_id, ward_number, geometry, 'v2'
      FROM public.wards
     ORDER BY ward_number;

    -- ---------------------------------------------------------------- 2. replace geometry + source (by ward_number)
    UPDATE public.wards w
       SET geometry = n.geom,
           source   = '""" + SOURCE + r"""'
      FROM v3_ward_geom n
     WHERE n.ward_number = w.ward_number;
    GET DIAGNOSTICS v_n = ROW_COUNT;
    IF v_n <> 23 THEN
        RAISE EXCEPTION 'V3: updated % ward rows, expected 23', v_n;
    END IF;

    SELECT coalesce(sum(ST_Area(ST_Intersection(a.geometry, b.geometry)::geography)), 0)
      INTO v_overlap
      FROM public.wards a
      JOIN public.wards b ON a.ward_number < b.ward_number AND ST_Intersects(a.geometry, b.geometry);
    IF v_overlap >= 1 THEN
        RAISE EXCEPTION 'V3: new ward geometries overlap by % m2', round(v_overlap::numeric, 3);
    END IF;

    -- ---------------------------------------------------------------- 3. complaints
    CREATE TEMP TABLE v3_complaint_ward ON COMMIT DROP AS
    SELECT c.complaint_id,
           c.ward_id AS old_ward_id,
           COALESCE(
               (SELECT w.ward_id FROM public.wards w
                 WHERE ST_Covers(w.geometry, c.location)
                 ORDER BY ST_Area(w.geometry), w.ward_number LIMIT 1),
               (SELECT w.ward_id FROM public.wards w
                 ORDER BY ST_Distance(w.geometry::geography, c.location::geography), w.ward_number LIMIT 1)
           ) AS new_ward_id
      FROM public.complaints c;

    INSERT INTO public.ward_reassignment_log (entity, entity_id, old_ward_id, new_ward_id)
    SELECT 'complaint', complaint_id, old_ward_id, new_ward_id
      FROM v3_complaint_ward
     WHERE old_ward_id IS DISTINCT FROM new_ward_id
     ORDER BY complaint_id;

    UPDATE public.complaints c
       SET ward_id = t.new_ward_id
      FROM v3_complaint_ward t
     WHERE t.complaint_id = c.complaint_id
       AND c.ward_id IS DISTINCT FROM t.new_ward_id;
    GET DIAGNOSTICS v_complaint = ROW_COUNT;

    -- ---------------------------------------------------------------- 4. pois (same point rule)
    CREATE TEMP TABLE v3_poi_ward ON COMMIT DROP AS
    SELECT p.poi_id,
           p.ward_id AS old_ward_id,
           COALESCE(
               (SELECT w.ward_id FROM public.wards w
                 WHERE ST_Covers(w.geometry, p.geometry)
                 ORDER BY ST_Area(w.geometry), w.ward_number LIMIT 1),
               (SELECT w.ward_id FROM public.wards w
                 ORDER BY ST_Distance(w.geometry::geography, p.geometry::geography), w.ward_number LIMIT 1)
           ) AS new_ward_id
      FROM public.pois p;

    INSERT INTO public.ward_reassignment_log (entity, entity_id, old_ward_id, new_ward_id)
    SELECT 'poi', poi_id, old_ward_id, new_ward_id
      FROM v3_poi_ward
     WHERE old_ward_id IS DISTINCT FROM new_ward_id
     ORDER BY poi_id;

    UPDATE public.pois p
       SET ward_id = t.new_ward_id
      FROM v3_poi_ward t
     WHERE t.poi_id = p.poi_id
       AND p.ward_id IS DISTINCT FROM t.new_ward_id;
    GET DIAGNOSTICS v_poi = ROW_COUNT;

    -- ---------------------------------------------------------------- 5. roads (largest length share)
    CREATE TEMP TABLE v3_road_ward ON COMMIT DROP AS
    SELECT r.road_id,
           r.ward_id AS old_ward_id,
           COALESCE(
               (SELECT w.ward_id FROM public.wards w
                 WHERE ST_Intersects(w.geometry, r.geometry)
                 ORDER BY ST_Length(ST_Intersection(r.geometry, w.geometry)::geography) DESC, w.ward_number LIMIT 1),
               (SELECT w.ward_id FROM public.wards w
                 ORDER BY ST_Distance(w.geometry::geography, r.geometry::geography), w.ward_number LIMIT 1)
           ) AS new_ward_id
      FROM public.roads r;

    INSERT INTO public.ward_reassignment_log (entity, entity_id, old_ward_id, new_ward_id)
    SELECT 'road', road_id, old_ward_id, new_ward_id
      FROM v3_road_ward
     WHERE old_ward_id IS DISTINCT FROM new_ward_id
     ORDER BY road_id;

    UPDATE public.roads r
       SET ward_id = t.new_ward_id
      FROM v3_road_ward t
     WHERE t.road_id = r.road_id
       AND r.ward_id IS DISTINCT FROM t.new_ward_id;
    GET DIAGNOSTICS v_road = ROW_COUNT;

    -- ---------------------------------------------------------------- postconditions
    IF EXISTS (SELECT 1 FROM public.complaints WHERE ward_id IS NULL)
       OR EXISTS (SELECT 1 FROM public.pois WHERE ward_id IS NULL)
       OR EXISTS (SELECT 1 FROM public.roads WHERE ward_id IS NULL) THEN
        RAISE EXCEPTION 'V3: some complaints / pois / roads have no ward after re-assignment';
    END IF;

    RAISE NOTICE 'V3: 23 ward geometries replaced (v2); re-assigned % complaints, % pois, % roads (see ward_reassignment_log)',
        v_complaint, v_poi, v_road;
END
$v3$;

COMMIT;
"""
open('/home/claude/civicbrain_deliverables/db/V3__wards_topology_clean.sql', 'w').write(sql)
print(len(sql))
