-- Flyway copy: identical to db/V4__security_privacy_jobs.sql without the outer BEGIN;/COMMIT; (Flyway wraps each migration in a transaction).
-- =============================================================================
-- CivicBrain | V4__security_privacy_jobs.sql
-- Adds what the security review (OWASP ASVS 5.0 L2) and India's DPDP Act/Rules need,
-- plus a PostgreSQL job queue (no Redis) for the AI worker.
--
-- Order   : run AFTER V2__civicbrain_app_layer.sql and V3__wards_topology_clean.sql
-- Target  : PostgreSQL 16-18 + PostGIS 3.4+   (tested on PG 16.13 + PostGIS 3.4.2)
-- Rules   : additive only, idempotent, one transaction. No existing row values change
--           (new columns get defaults; ADD COLUMN does not fire row triggers).
-- =============================================================================
SET LOCAL search_path = public;

-- -----------------------------------------------------------------------------
-- 1. Staff MFA (TOTP) and token revocation
-- -----------------------------------------------------------------------------
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS totp_secret_enc     text,                          -- AES-GCM encrypted by the backend, never plain
    ADD COLUMN IF NOT EXISTS totp_enabled        boolean     NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS totp_last_used_step bigint,                        -- blocks replay of the same 30 s code
    ADD COLUMN IF NOT EXISTS token_valid_after   timestamptz NOT NULL DEFAULT now(); -- access JWTs issued before this are rejected

COMMENT ON COLUMN users.token_valid_after IS
  'Logout-all, password change, role change, disable: set to now(); JWTs with iat < token_valid_after are rejected.';
COMMENT ON COLUMN users.totp_secret_enc IS
  'Base64(IV || AES-256-GCM ciphertext) of the RFC 6238 secret. Key from env CIVICBRAIN_TOTP_KEY. Required for OFFICER and ADMIN.';

ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_totp;
ALTER TABLE users ADD  CONSTRAINT ck_users_totp CHECK (NOT totp_enabled OR totp_secret_enc IS NOT NULL);

-- -----------------------------------------------------------------------------
-- 2. Privacy notice, consent and data-principal requests (DPDP Act 2023 / Rules 2025)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS privacy_notices (
    version        varchar(20) PRIMARY KEY,
    published_at   timestamptz NOT NULL DEFAULT now(),
    summary        text        NOT NULL,
    content_hash   char(64),
    is_current     boolean     NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_privacy_notice_current ON privacy_notices ((true)) WHERE is_current;

INSERT INTO privacy_notices (version, summary, is_current) VALUES
  ('2026-10-v1',
   'CivicBrain collects your name, phone, e-mail, complaint text, photos and GPS location to register and resolve civic complaints for Talegaon Dabhade Municipal Council. Photos are shown publicly only after blurring and officer approval, and only if you allow it. You can ask to see, correct or delete your data and withdraw consent from your profile page.',
   true)
ON CONFLICT (version) DO NOTHING;

CREATE TABLE IF NOT EXISTS user_consents (
    consent_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         bigint      NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    consent_type    varchar(30) NOT NULL,
    granted         boolean     NOT NULL,
    notice_version  varchar(20) NOT NULL REFERENCES privacy_notices(version),
    created_at      timestamptz NOT NULL DEFAULT now(),
    ip_address      inet,
    CONSTRAINT ck_consent_type CHECK (consent_type IN ('PRIVACY_NOTICE','PUBLIC_PHOTO','AI_TRAINING','WHATSAPP_MESSAGES'))
);
CREATE INDEX IF NOT EXISTS idx_user_consents_user ON user_consents (user_id, consent_type, created_at DESC);

-- latest decision per user and consent type (consents are append-only history)
CREATE OR REPLACE VIEW v_current_consents AS
SELECT DISTINCT ON (user_id, consent_type)
       user_id, consent_type, granted, notice_version, created_at
  FROM user_consents
 ORDER BY user_id, consent_type, created_at DESC, consent_id DESC;

CREATE TABLE IF NOT EXISTS data_subject_requests (
    request_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        bigint      NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    request_type   varchar(20) NOT NULL,
    status         varchar(20) NOT NULL DEFAULT 'RECEIVED',
    details        text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    due_at         timestamptz NOT NULL DEFAULT (now() + interval '90 days'),
    completed_at   timestamptz,
    handled_by     bigint REFERENCES users(user_id) ON DELETE SET NULL,
    resolution     text,
    CONSTRAINT ck_dsr_type   CHECK (request_type IN ('ACCESS','CORRECTION','ERASURE','WITHDRAW_CONSENT','GRIEVANCE')),
    CONSTRAINT ck_dsr_status CHECK (status IN ('RECEIVED','IN_PROGRESS','COMPLETED','REJECTED')),
    CONSTRAINT ck_dsr_done   CHECK (status NOT IN ('COMPLETED','REJECTED') OR completed_at IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_dsr_status ON data_subject_requests (status, due_at);

-- -----------------------------------------------------------------------------
-- 3. Public photos only after blurring + officer approval
-- -----------------------------------------------------------------------------
ALTER TABLE complaint_images
    ADD COLUMN IF NOT EXISTS public_approved      boolean NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS blurred_storage_key  text,
    ADD COLUMN IF NOT EXISTS approved_by          bigint REFERENCES users(user_id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS approved_at          timestamptz;
ALTER TABLE complaint_images DROP CONSTRAINT IF EXISTS ck_complaint_images_public;
ALTER TABLE complaint_images ADD  CONSTRAINT ck_complaint_images_public CHECK (
    NOT public_approved OR (blurred_storage_key IS NOT NULL AND approved_by IS NOT NULL AND approved_at IS NOT NULL));

-- Public map: no personal data, location snapped to a ~220 m grid, rejected/merged hidden
CREATE OR REPLACE VIEW v_public_complaint_map AS
SELECT c.public_ref,
       cat.category_name,
       cat.work_type_code,
       CASE WHEN c.status IN ('SUBMITTED','VERIFIED','REOPENED')                THEN 'OPEN'
            WHEN c.status IN ('SCHEDULED','ASSIGNED','INSPECTED','IN_PROGRESS') THEN 'IN_PROGRESS'
            ELSE 'RESOLVED' END                                                AS public_status,
       w.ward_number,
       round(ST_Y(ST_SnapToGrid(c.location, 0.002))::numeric, 3)               AS latitude,
       round(ST_X(ST_SnapToGrid(c.location, 0.002))::numeric, 3)               AS longitude,
       c.submitted_at::date                                                    AS reported_on,
       (SELECT count(*) FROM complaint_votes v WHERE v.complaint_id = c.complaint_id AND v.vote_type = 'UP') AS supporters,
       c.is_synthetic
  FROM complaints c
  LEFT JOIN complaint_categories cat ON cat.category_id = c.category_id
  LEFT JOIN wards w                  ON w.ward_id = c.ward_id
 WHERE c.status NOT IN ('REJECTED','MERGED')
   AND c.master_complaint_id IS NULL;

-- -----------------------------------------------------------------------------
-- 4. Job queue for the Python worker (replaces Redis/RQ)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS jobs (
    job_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type      varchar(40) NOT NULL,
    ref_id        bigint      NOT NULL,                   -- complaint_id, image_id, run_id ...
    payload       jsonb       NOT NULL DEFAULT '{}'::jsonb,
    status        varchar(20) NOT NULL DEFAULT 'QUEUED',
    priority      smallint    NOT NULL DEFAULT 100,       -- lower = sooner
    attempts      integer     NOT NULL DEFAULT 0,
    max_attempts  integer     NOT NULL DEFAULT 3,
    run_after     timestamptz NOT NULL DEFAULT now(),
    locked_by     text,
    locked_at     timestamptz,
    last_error    text,
    created_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    CONSTRAINT ck_jobs_type   CHECK (job_type IN ('ANALYZE_COMPLAINT','ANALYZE_IMAGE','OPTIMIZE_PLAN','BLUR_IMAGE','RENDER_EXPORT')),
    CONSTRAINT ck_jobs_status CHECK (status IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','DEAD')),
    CONSTRAINT ck_jobs_attempts CHECK (attempts >= 0 AND max_attempts > 0)
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_jobs_active ON jobs (job_type, ref_id) WHERE status IN ('QUEUED','RUNNING');
CREATE INDEX IF NOT EXISTS idx_jobs_pick ON jobs (priority, run_after) WHERE status = 'QUEUED';

-- Claim up to p_limit due jobs atomically (safe with several workers)
CREATE OR REPLACE FUNCTION fn_claim_jobs(p_worker text, p_types text[], p_limit integer DEFAULT 1)
RETURNS SETOF jobs
LANGUAGE sql AS $$
    UPDATE jobs j
       SET status = 'RUNNING', locked_by = p_worker, locked_at = now(), attempts = j.attempts + 1
     WHERE j.job_id IN (SELECT q.job_id
                          FROM jobs q
                         WHERE q.status = 'QUEUED'
                           AND q.run_after <= now()
                           AND q.job_type = ANY (p_types)
                         ORDER BY q.priority, q.run_after, q.job_id
                         LIMIT p_limit
                         FOR UPDATE SKIP LOCKED)
    RETURNING j.*;
$$;

-- Finish a job; failures retry with backoff 1 min, 5 min, 25 min ... then DEAD
CREATE OR REPLACE FUNCTION fn_finish_job(p_job_id bigint, p_success boolean, p_error text DEFAULT NULL)
RETURNS varchar
LANGUAGE plpgsql AS $$
DECLARE
    v_job jobs%ROWTYPE;
    v_new varchar;
BEGIN
    SELECT * INTO v_job FROM jobs WHERE job_id = p_job_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Job % not found', p_job_id;
    END IF;
    IF v_job.status <> 'RUNNING' THEN
        RAISE EXCEPTION 'Job % is % (only RUNNING jobs can be finished)', p_job_id, v_job.status;
    END IF;
    IF p_success THEN
        v_new := 'SUCCEEDED';
        UPDATE jobs SET status = v_new, finished_at = now(), last_error = NULL, locked_by = NULL, locked_at = NULL
         WHERE job_id = p_job_id;
    ELSIF v_job.attempts >= v_job.max_attempts THEN
        v_new := 'DEAD';
        UPDATE jobs SET status = v_new, finished_at = now(), last_error = left(p_error, 4000), locked_by = NULL, locked_at = NULL
         WHERE job_id = p_job_id;
    ELSE
        v_new := 'QUEUED';
        UPDATE jobs SET status = v_new, last_error = left(p_error, 4000), locked_by = NULL, locked_at = NULL,
                        run_after = now() + interval '1 minute' * power(5, v_job.attempts - 1)
         WHERE job_id = p_job_id;
    END IF;
    RETURN v_new;
END $$;

-- A crashed worker leaves RUNNING jobs behind: put them back after p_stale
CREATE OR REPLACE FUNCTION fn_requeue_stale_jobs(p_stale interval DEFAULT interval '15 minutes')
RETURNS integer
LANGUAGE plpgsql AS $$
DECLARE v_count integer;
BEGIN
    UPDATE jobs SET status = CASE WHEN attempts >= max_attempts THEN 'DEAD' ELSE 'QUEUED' END,
                    locked_by = NULL, locked_at = NULL,
                    last_error = coalesce(last_error, '') || ' [requeued: stale lock]'
     WHERE status = 'RUNNING' AND locked_at < now() - p_stale;
    GET DIAGNOSTICS v_count = ROW_COUNT;
    RETURN v_count;
END $$;

-- Every real complaint is analysed: the job is created in the SAME transaction as the insert
CREATE OR REPLACE FUNCTION fn_enqueue_complaint_analysis() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NOT NEW.is_synthetic THEN
        INSERT INTO jobs (job_type, ref_id, priority)
        VALUES ('ANALYZE_COMPLAINT', NEW.complaint_id, 50)
        ON CONFLICT (job_type, ref_id) WHERE status IN ('QUEUED','RUNNING') DO NOTHING;
    END IF;
    RETURN NULL;
END $$;

CREATE OR REPLACE TRIGGER trg_complaints_enqueue_analysis
    AFTER INSERT ON complaints
    FOR EACH ROW EXECUTE FUNCTION fn_enqueue_complaint_analysis();

CREATE OR REPLACE FUNCTION fn_enqueue_optimizer_run() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'QUEUED' THEN
        INSERT INTO jobs (job_type, ref_id, priority)
        VALUES ('OPTIMIZE_PLAN', NEW.run_id, 20)
        ON CONFLICT (job_type, ref_id) WHERE status IN ('QUEUED','RUNNING') DO NOTHING;
    END IF;
    RETURN NULL;
END $$;

CREATE OR REPLACE TRIGGER trg_optimizer_runs_enqueue
    AFTER INSERT ON optimizer_runs
    FOR EACH ROW EXECUTE FUNCTION fn_enqueue_optimizer_run();

-- -----------------------------------------------------------------------------
-- 5. Retention housekeeping (called daily by the backend scheduler)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_purge_expired()
RETURNS TABLE (item text, deleted bigint)
LANGUAGE plpgsql
SECURITY DEFINER            -- runs as the owner: the app role has no DELETE on auth_events (append-only)
SET search_path = public
AS $$
DECLARE n bigint;
BEGIN
    DELETE FROM auth_otp_codes WHERE created_at < now() - interval '30 days';
    GET DIAGNOSTICS n = ROW_COUNT; item := 'auth_otp_codes > 30 d'; deleted := n; RETURN NEXT;

    DELETE FROM auth_refresh_tokens WHERE expires_at < now() - interval '30 days';
    GET DIAGNOSTICS n = ROW_COUNT; item := 'expired refresh tokens > 30 d'; deleted := n; RETURN NEXT;

    DELETE FROM capture_sessions WHERE issued_at < now() - interval '7 days' AND used_at IS NULL;
    GET DIAGNOSTICS n = ROW_COUNT; item := 'unused capture sessions > 7 d'; deleted := n; RETURN NEXT;

    DELETE FROM jobs WHERE status = 'SUCCEEDED' AND finished_at < now() - interval '90 days';
    GET DIAGNOSTICS n = ROW_COUNT; item := 'succeeded jobs > 90 d'; deleted := n; RETURN NEXT;

    DELETE FROM auth_events WHERE created_at < now() - interval '365 days';
    GET DIAGNOSTICS n = ROW_COUNT; item := 'auth events > 365 d'; deleted := n; RETURN NEXT;
END $$;

